package com.sc.overhub.domain.model.statistics.heroes

data class GeneralStats(
    val cards: Double,
    val damage_done: Double,
    val damage_done_most_in_game: Double,
    val damage_done_most_in_life: Double,
    val deaths: Double,
    val eliminations: Double,
    val eliminations_most_in_game: Double,
    val eliminations_most_in_life: Double,
    val eliminations_per_life: Double,
    val environmental_deaths: Double,
    val environmental_kills: Double,
    val final_blows: Double,
    val final_blows_most_in_game: Double,
    val games_won: Double,
    val kill_streak_best: Double,
    val medals: Double,
    val medals_bronze: Double,
    val medals_gold: Double,
    val medals_silver: Double,
    val melee_final_blow: Double,
    val multikill_best: Double,
    val multikills: Double,
    val objective_kills: Double,
    val objective_kills_most_in_game: Double,
    val objective_time: String,
    val objective_time_most_in_game: String,
    val solo_kills: Double,
    val solo_kills_most_in_game: Double,
    val teleporter_pads_destroyed: Double,
    val time_played: String,
    val time_spent_on_fire: String,
    val weapon_accuracy: String
)